name: Workflow Notifly

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm run test